import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "remixicon/fonts/remixicon.css";
import FormProvider from "@/context/FormContext";
import Navbar from "@/components/Navbar";
import NextTopLoader from "nextjs-toploader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Job Portal",
  description: "Generated by create next app",
  icons: {
    icon: "/job-logo.png?v=2",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-screen w-screen overflow-hidden">
          <Navbar />
          <div className="h-full w-full overflow-y-auto pb-20">
            <FormProvider>{children}</FormProvider>
          </div>
        </div>
        <NextTopLoader showSpinner={false} color="#6366F1" />
      </body>
    </html>
  );
}
