export const fieldsOfStudy = [
  "Accounting",
  "Advertising",
  "Aerospace Engineering",
  "Agriculture",
  "Algorithm Design and Analysis",
  "Anthropology",
  "Animation",
  "Architecture",
  "Art and Design",
  "Artificial Intelligence",
  "Astronomy",
  "Augmented Reality (AR)",
  "Automotive Engineering",
  "Big Data Engineering",
  "Bioinformatics",
  "Biochemistry",
  "Biology",
  "Biomedical Engineering",
  "Blockchain Technology",
  "Botany",
  "Broadcasting",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Cloud Architecture",
  "Cloud Computing",
  "Commerce",
  "Communication Studies",
  "Comparative Religion",
  "Computational Biology",
  "Computational Linguistics",
  "Computer Architecture",
  "Computer Engineering",
  "Computer Graphics",
  "Computer Networks",
  "Computer Science",
  "Computer Vision",
  "Criminology",
  "Cultural Studies",
  "Cybersecurity",
  "Data Analytics",
  "Data Science",
  "Database Administration",
  "Database Systems",
  "Dentistry",
  "Design",
  "DevOps",
  "Digital Forensics",
  "Digital Media Design",
  "E-Business",
  "E-Commerce Technology",
  "Economics",
  "Education",
  "Electrical Engineering",
  "Electronics Engineering",
  "Embedded Systems",
  "Energy Engineering",
  "Entrepreneurship",
  "Environmental Engineering",
  "Environmental Science",
  "Event Management",
  "Fashion Design",
  "Film and Media Studies",
  "Finance",
  "Fine Arts",
  "Food Science",
  "Game Development",
  "Genetics",
  "Geographic Information Systems (GIS)",
  "Geography",
  "Geology",
  "Graphic Design",
  "Health Sciences",
  "History",
  "Hospitality Management",
  "Human-Computer Interaction (HCI)",
  "Human Resource Management",
  "Industrial Design",
  "Industrial Engineering",
  "Information Security",
  "Information Systems",
  "Information Technology",
  "Interior Design",
  "International Business",
  "International Relations",
  "Internet of Things (IoT)",
  "IT Project Management",
  "Journalism",
  "Law",
  "Library and Information Science",
  "Linguistics",
  "Literature",
  "Logistics and Transportation",
  "Machine Learning",
  "Management",
  "Marine Biology",
  "Marketing",
  "Mass Communication",
  "Materials Engineering",
  "Mathematics",
  "Mechanical Engineering",
  "Mechatronics Engineering",
  "Media Studies",
  "Medical Laboratory Science",
  "Medicine",
  "Microbiology",
  "Mobile App Development",
  "Molecular Biology",
  "Music",
  "Nanotechnology",
  "Network Security",
  "Nursing",
  "Nutrition",
  "Operations Management",
  "Operating Systems",
  "Parallel and Distributed Computing",
  "Performing Arts",
  "Pharmacy",
  "Philosophy",
  "Photography",
  "Physics",
  "Physiotherapy",
  "Political Science",
  "Project Management",
  "Programming Languages",
  "Psychology",
  "Public Administration",
  "Public Health",
  "Public Relations",
  "Quantum Computing",
  "Radiology",
  "Religious Studies",
  "Robotics",
  "Social Work",
  "Sociology",
  "Software Engineering",
  "Software Testing and Quality Assurance",
  "Sports Science",
  "Statistics",
  "Structural Engineering",
  "Supply Chain Management",
  "Systems Analysis",
  "Telecommunication Engineering",
  "Theology",
  "Tourism and Hospitality Management",
  "Urban Planning",
  "UI/UX Design",
  "Virtual Reality (VR)",
  "Visual Communication",
  "Veterinary Medicine",
  "Web Development",
  "Zoology",
];
